FROM apache/airflow:2.9.1-python3.11

WORKDIR /opt/airflow

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-ansi