FROM apache/airflow:2.9.2-python3.11

# Instalacja Poetry
USER root
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

# Kopiujemy pliki zależności
COPY requirements.txt /tmp/requirements.txt

# Instalacja zależności w kontenerze
USER airflow
RUN pip install -r /tmp/requirements.txt


# Ustawienia środowiska
ENV AIRFLOW_HOME=/opt/airflow
WORKDIR $AIRFLOW_HOME
